### ISSUE TITLE
[4.0] Remove dependency on Polymer library

### ISSUE THREAD

**Issue by t2ym** [t2ym/i18n-number#17]
[4.0] Remove dependency on Polymer library

## Status
- Part of https://github.com/t2ym/i18n-element/issues/63
- WIP in [4.0-develop](https://github.com/t2ym/i18n-number/tree/4.0-develop) branch
- NPM package
  - `npm install i18n-number@next` or `npm install i18n-number@4.0.0-pre.6`

## Tasks
- [x] Move `@polymer/polymer` from dependencies to devDependencies
- [x] Drop Safari 9 support
  - [x] Remove `intl` package dependency
- [x] `bower.json` with `BSD-2-Clause` as `license`
- [x] Add `lit-html` dependency
- [x] Remove `intl` loading mechanism
- [x] Convert to `lit-html` rendering
  - [x] Remove `@polymer/polymer` imports
  - [x] Convert properties and observers
- [x] Support IE11 and Edge with custom elements v1 polyfill
  - [x] ~~Temporarily insert `polyfill.js` contents from `i18n-element/polyfill.js`~~
  - [x] Import a separate `polyfill.js` from an independent npm module for `polyfill.js`
    - [x] Create npm package `wc-putty` and import
- [x] Convert tests
  - [x] No Polymer methods
  - [x] Add some waits
- [ ] Convert demo
  - [x] Remove `intl` from `extraDependencies` in `polymer.json`
- [ ] Documentation
  - [ ] Decent comments
  - [ ] API Docs page

## Design Issues
- [x] How to port `notifyPath()` feature from Polymer?
  - [x] Just call `_onOptionsPropertyChanged()`
- [x] Is `reflectToAttribute` feature required? No
- [x] `root` property for `shadowRoot` to imitate a Polymer element
- [x] Should `attachShadow()` be put off until the first rendering like `i18n-format`? Yes
  - `i18n-element` tests fail with `<plural-gender-element>`
- [x] Should assignment of `this.lang` with the default value be put off until `connectedCallback`? Yes
- [x] Is `importMeta` property necessary? No.

## Issues
- [x] `document.createElement('i18n-number')` fails with "The result must not have attributes"
  - [x] Fix: Put off setting `this.lang` in the constructor to the next microtask timing
  - [x] Fix: Add `'null'` guards for `lang` property
- [x] `lang` attribute/property is unexpectedly set to `"en"`
```javascript
window.t = document.createElement('template');
t.innerHTML = '<i18n-number id="overridden-lang" lang="fr">12.34</i18n-number>'
document.body.appendChild(t.content);
document.querySelector('i18n-number#overridden-lang').lang === 'fr' // must be true, actually false
```
  - Root Cause: `lang` has to be set at `connectedCallback` instead of the microtask timing after constructor
